SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `MEREMPRESAC` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

USE `MEREMPRESAC`;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`PERSONA` (
  `Codigo` INT(11) NOT NULL ,
  `Documento` INT(11) NOT NULL ,
  `Nombre` VARCHAR(45) NOT NULL ,
  `Apellido` VARCHAR(45) NOT NULL ,
  `Genero` ENUM('masculino', 'femenino') NOT NULL ,
  `Correo` VARCHAR(45) NOT NULL ,
  `Telefono` INT(11) NOT NULL ,
  `Direccion` VARCHAR(45) NOT NULL ,
  `Rol` ENUM('Administrador', 'Vendedor', 'Cliente', 'Proveedor') NOT NULL ,
  `Password` VARCHAR(45) NULL DEFAULT NULL ,
  `Estado` ENUM('activo', 'inactivo') NOT NULL ,
  PRIMARY KEY (`Codigo`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`PRODUCTO` (
  `Codigo` INT(11) NOT NULL ,
  `Nombre` VARCHAR(45) NOT NULL ,
  `Importado` TINYINT(1) NOT NULL ,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL ,
  `Marca` INT(11) NOT NULL ,
  `Subcategoria` INT(11) NOT NULL ,
  `Estado` ENUM('Activo', 'Agotado') NOT NULL ,
  PRIMARY KEY (`Codigo`) ,
  INDEX `fk_PRODUCTO_MARCA1_idx` (`Marca` ASC) ,
  INDEX `fk_PRODUCTO_SUBCATEGORIA1_idx` (`Subcategoria` ASC) ,
  CONSTRAINT `fk_PRODUCTO_MARCA1`
    FOREIGN KEY (`Marca` )
    REFERENCES `MEREMPRESAC`.`MARCA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_SUBCATEGORIA1`
    FOREIGN KEY (`Subcategoria` )
    REFERENCES `MEREMPRESAC`.`SUBCATEGORIA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`MARCA` (
  `Codigo` INT(11) NOT NULL ,
  `Nombre` VARCHAR(45) NOT NULL ,
  `Descripcion` VARCHAR(45) NOT NULL ,
  `Estado` ENUM('activo', 'inactivo') NOT NULL ,
  PRIMARY KEY (`Codigo`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`CATEGORIA` (
  `Codigo` INT(11) NOT NULL ,
  `Nombre` VARCHAR(45) NOT NULL ,
  `Descripcion` VARCHAR(45) NOT NULL ,
  `Estado` ENUM('activo', 'inactivo') NOT NULL ,
  PRIMARY KEY (`Codigo`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`VENTA` (
  `Codigo` INT(11) NOT NULL ,
  `Fecha` DATE NOT NULL ,
  `Vendendor` INT(11) NOT NULL ,
  `Cliente` INT(11) NOT NULL ,
  `Sede` INT(11) NOT NULL ,
  `MetodoPago` ENUM('Tarjeta de Credito', 'Efectivo', 'Cheque') NOT NULL ,
  `Total` DOUBLE NOT NULL ,
  `Estado` ENUM('Pendiente', 'Finalizada') NOT NULL ,
  PRIMARY KEY (`Codigo`) ,
  INDEX `fk_VENTA_PERSONA_idx` (`Vendendor` ASC) ,
  INDEX `fk_VENTA_PERSONA1_idx` (`Cliente` ASC) ,
  INDEX `fk_VENTA_Sede1_idx` (`Sede` ASC) ,
  CONSTRAINT `fk_VENTA_PERSONA`
    FOREIGN KEY (`Vendendor` )
    REFERENCES `MEREMPRESAC`.`PERSONA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTA_PERSONA1`
    FOREIGN KEY (`Cliente` )
    REFERENCES `MEREMPRESAC`.`PERSONA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTA_Sede1`
    FOREIGN KEY (`Sede` )
    REFERENCES `MEREMPRESAC`.`SEDE` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`COMPRA` (
  `Codigo` INT(11) NOT NULL ,
  `Fecha` DATE NOT NULL ,
  `Sede` INT(11) NOT NULL ,
  `Proveedor` INT(11) NOT NULL ,
  `Total` INT(11) NOT NULL ,
  `Estado` ENUM('En Proceso', 'Finalizada') NOT NULL ,
  PRIMARY KEY (`Codigo`) ,
  INDEX `fk_COMPRA_Sede1_idx` (`Sede` ASC) ,
  INDEX `fk_COMPRA_PERSONA1_idx` (`Proveedor` ASC) ,
  CONSTRAINT `fk_COMPRA_Sede1`
    FOREIGN KEY (`Sede` )
    REFERENCES `MEREMPRESAC`.`SEDE` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRA_PERSONA1`
    FOREIGN KEY (`Proveedor` )
    REFERENCES `MEREMPRESAC`.`PERSONA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`INVENTARIO` (
  `Codigo` INT(11) NOT NULL ,
  `Producto` INT(11) NOT NULL ,
  `Compra` INT(11) NOT NULL ,
  `Cantidad` INT(10) UNSIGNED NOT NULL ,
  `Precio` INT(11) NOT NULL ,
  `IVA` INT(11) NOT NULL ,
  `Talla` ENUM('S', 'M', 'L', 'X', 'XL') NOT NULL ,
  `Color` ENUM('Rojo', 'Verde', 'Azul') NOT NULL ,
  PRIMARY KEY (`Codigo`) ,
  INDEX `fk_INVENTARIO_PRODUCTO1_idx` (`Producto` ASC) ,
  INDEX `fk_INVENTARIO_COMPRA1_idx` (`Compra` ASC) ,
  CONSTRAINT `fk_INVENTARIO_PRODUCTO1`
    FOREIGN KEY (`Producto` )
    REFERENCES `MEREMPRESAC`.`PRODUCTO` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTARIO_COMPRA1`
    FOREIGN KEY (`Compra` )
    REFERENCES `MEREMPRESAC`.`COMPRA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`DESCUENTO` (
  `Codigo` INT(11) NOT NULL ,
  `Nombre` VARCHAR(45) NOT NULL ,
  `Porcentaje` FLOAT(11) NOT NULL ,
  `Fecha_inicio` DATE NOT NULL ,
  `Fecha_fin` DATE NOT NULL ,
  `Producto` INT(11) NOT NULL ,
  PRIMARY KEY (`Codigo`) ,
  INDEX `fk_PROMOCION_PRODUCTO1_idx` (`Producto` ASC) ,
  CONSTRAINT `fk_PROMOCION_PRODUCTO1`
    FOREIGN KEY (`Producto` )
    REFERENCES `MEREMPRESAC`.`PRODUCTO` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`ITEM-VENTA` (
  `Codigo` INT(11) NOT NULL ,
  `Venta` INT(11) NOT NULL ,
  `Inventario` INT(11) NOT NULL ,
  `Cantidad` INT(11) NOT NULL ,
  `Precio` INT(11) NOT NULL ,
  `IVA` INT(11) NOT NULL ,
  `PrecioTotal` INT(11) NOT NULL ,
  PRIMARY KEY (`Codigo`) ,
  INDEX `fk_ITEM-VENTA_VENTA1_idx` (`Venta` ASC) ,
  INDEX `fk_ITEM-VENTA_INVENTARIO1_idx` (`Inventario` ASC) ,
  CONSTRAINT `fk_ITEM-VENTA_VENTA1`
    FOREIGN KEY (`Venta` )
    REFERENCES `MEREMPRESAC`.`VENTA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM-VENTA_INVENTARIO1`
    FOREIGN KEY (`Inventario` )
    REFERENCES `MEREMPRESAC`.`INVENTARIO` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`SEDE` (
  `Codigo` INT(11) NOT NULL ,
  `Nombre` VARCHAR(45) NOT NULL ,
  `Direccion` VARCHAR(15) NOT NULL ,
  `Encargado` INT(11) NOT NULL ,
  PRIMARY KEY (`Codigo`) ,
  INDEX `fk_sede_PERSONA1_idx` (`Encargado` ASC) ,
  CONSTRAINT `fk_sede_PERSONA1`
    FOREIGN KEY (`Encargado` )
    REFERENCES `MEREMPRESAC`.`PERSONA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`SUBCATEGORIA` (
  `Codigo` INT(11) NOT NULL ,
  `Nombre` VARCHAR(45) NOT NULL ,
  `Descripcion` VARCHAR(45) NOT NULL ,
  `Estado` ENUM('activo', 'inactivo') NOT NULL ,
  `Categoria` INT(11) NOT NULL ,
  PRIMARY KEY (`Codigo`) ,
  INDEX `fk_SUBCATEGORIA_CATEGORIA1_idx` (`Categoria` ASC) ,
  CONSTRAINT `fk_SUBCATEGORIA_CATEGORIA1`
    FOREIGN KEY (`Categoria` )
    REFERENCES `MEREMPRESAC`.`CATEGORIA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `MEREMPRESAC`.`ABONO` (
  `Codigo` VARCHAR(45) NOT NULL ,
  `Venta` INT(11) NOT NULL ,
  `Fecha` DATETIME NOT NULL ,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL ,
  `MetodoPago` ENUM('Tarjeta de Credito', 'Efectivo', 'Cheque') NOT NULL ,
  `Valor` DOUBLE NOT NULL ,
  INDEX `Venta_cod_idx` (`Venta` ASC) ,
  PRIMARY KEY (`Codigo`) ,
  CONSTRAINT `Venta_cod`
    FOREIGN KEY (`Venta` )
    REFERENCES `MEREMPRESAC`.`VENTA` (`Codigo` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
